# Generated by Django 3.2.6 on 2023-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YOB', models.IntegerField()),
                ('NKID', models.IntegerField()),
                ('DEP', models.IntegerField()),
                ('PHON', models.BinaryField()),
                ('SINC', models.IntegerField()),
                ('AES', models.CharField(max_length=50)),
                ('DAINC', models.IntegerField()),
                ('RES', models.CharField(max_length=50)),
                ('DHVAL', models.IntegerField()),
                ('DMORT', models.IntegerField()),
                ('DOUTM', models.IntegerField()),
                ('DOUTL', models.IntegerField()),
                ('DOUTHP', models.IntegerField()),
                ('DOUTCC', models.IntegerField()),
            ],
        ),
    ]
