# Generated by Django 3.2.6 on 2023-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_pret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('YOB', models.IntegerField()),
                ('NKID', models.IntegerField()),
                ('DEP', models.IntegerField()),
                ('PHON', models.IntegerField()),
                ('SINC', models.IntegerField()),
                ('AES', models.CharField(default='anonyme', max_length=30)),
                ('DAINC', models.IntegerField()),
                ('RES', models.CharField(default='anonyme', max_length=30)),
                ('DHVAL', models.IntegerField()),
                ('DMORT', models.IntegerField()),
                ('DOUTM', models.IntegerField()),
                ('DOUTL', models.IntegerField()),
                ('DOUTHP', models.IntegerField()),
                ('DOUTCC', models.IntegerField()),
            ],
        ),
    ]
