# Generated by Django 3.2.6 on 2023-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='name',
            field=models.CharField(default='anonyme', max_length=30),
        ),
    ]
