# Generated by Django 3.2.6 on 2023-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_credit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('name', models.CharField(default='anonyme', max_length=30)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('person_age', models.IntegerField()),
                ('person_income', models.DecimalField(decimal_places=2, max_digits=30)),
                ('person_home_ownership', models.CharField(default='anonyme', max_length=30)),
                ('person_emp_length', models.IntegerField()),
                ('loan_intent', models.CharField(default='anonyme', max_length=50)),
                ('loan_grade', models.CharField(default='anonyme', max_length=50)),
                ('loan_amnt', models.IntegerField()),
                ('loan_int_rate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('loan_status', models.IntegerField()),
                ('loan_percent_income', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cb_person_default_on_file', models.CharField(default='anonyme', max_length=50)),
                ('cb_person_cred_hist_length', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
