# Generated by Django 3.2.6 on 2023-05-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20230530_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee',
            name='loan_int_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='donnee',
            name='loan_percent_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
